//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// TS_WR_HS_FUSING.rc에서 사용되고 있습니다.
//
#define IDC_BTN_LOGIN                   1
#define IDD_TS_WR_HS_FUSING_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_FW_UPDATE_DIALOG            130
#define IDB_LOGO                        132
#define IDD_OPBOX_FUSING                133
#define IDD_SYSTEM_MENU                 134
#define IDD_CHECK_MODELNAME             135
#define IDD_SET_FLICKER                 137
#define IDC_SET_SYSTEM                  143
#define IDB_TEST                        152
#define IDB_SYSTEM                      154
#define IDB_BMP_USER_IMG                157
#define IDD_USER_LOGIN                  158
#define IDC_GRP_TIMMING                 1000
#define IDC_GRP_SIGNAL                  1001
#define IDC_GRP_PATTERN                 1002
#define IDC_CMB_TYPE                    1003
#define IDC_CMB_PIXEL                   1004
#define IDC_CMB_BIT                     1005
#define IDC_CMB_SWAP                    1006
#define IDC_CMB_BITSEL                  1007
#define IDC_CMB_LVSEL                   1008
#define IDC_GRP_GPIO                    1009
#define IDC_GRP_PWRSEQ                  1010
#define IDC_GRP_PWRVOLCUR               1011
#define IDC_SEQ1_SEL                    1012
#define IDC_SEQ2_SEL                    1013
#define IDC_GRP_PWRLIMIT                1014
#define IDC_GRP_SYSTEM                  1015
#define IDC_CMB_DIVISION                1016
#define IDC_CMB_DFORM                   1017
#define IDC_CMB_PEMPH                   1018
#define IDC_BTN_SAVE                    1019
#define IDC_BTN_FUSING                  1020
#define IDC_BTN_CLOSE                   1021
#define IDC_GRP_MODEL                   1022
#define IDC_EDT_MODEL                   1023
#define IDC_GRP_MODEL4                  1023
#define IDC_BTN_SAVEAS                  1024
#define IDC_STT_FILE_NAME               1024
#define IDC_GRP_MODEL5                  1024
#define IDC_CMB_GP1                     1025
#define IDC_STT_HEX_NAME                1025
#define IDC_CMB_GP2                     1026
#define IDC_BTN_BROWSE_HEX              1026
#define IDC_CMB_GP3                     1027
#define IDC_BTN_UPDATE                  1027
#define IDC_CMB_GP4                     1028
#define IDC_STT_STATUS                  1028
#define IDC_CMB_GP5                     1029
#define IDC_STT_PROGRESS                1029
#define IDC_CMB_GP6                     1030
#define IDC_CMB_GP7                     1031
#define IDC_CMB_GP8                     1032
#define IDC_CMB_COMPORT                 1033
#define IDC_BTN_PORT_OPEN               1034
#define IDC_BTN_FW_UPDATE               1035
#define IDC_LOGO                        1036
#define IDC_LEGO                        1036
#define IDC_CMB_BIT2                    1037
#define IDC_CMB_COPEN                   1037
#define IDC_LIST_SRC_MODEL              1037
#define IDC_LIST_FUSING_MODEL           1038
#define IDC_BTN_OPBOX                   1038
#define IDC_STT_SRC_MOD                 1039
#define IDC_GRP_COMMON                  1039
#define IDC_BTN_SEARCH                  1039
#define IDC_STT_FUSING_MOD              1040
#define IDC_BTN_SYSTEM_MENU             1040
#define IDC_GRP_VOLATILE                1040
#define IDC_BTN_ADD                     1041
#define IDC_GRP_NON_VOLATILE            1041
#define IDC_BTN_DEL                     1042
#define IDC_PIC_SELECT                  1042
#define IDC_BTN_UP                      1043
#define IDC_GRP_MODEL2                  1043
#define IDC_BTN_DN                      1044
#define IDC_GRP_MODEL3                  1044
#define IDC_STT_FUSING_MSG              1045
#define IDC_PIC_SYSTEM                  1045
#define IDC_STT_MODEL_NAME_PATH         1047
#define IDC_EDIT_MODELNAME_PATH         1048
#define IDC_BTN_MODELFILE_PATH          1049
#define IDC_EDIT_PATTERNNAME_PATH       1049
#define IDC_STT_SYSTEM_MENU_TITLE       1050
#define IDC_EDIT_MAIN_MODELPATH         1050
#define IDC_STT_CHECKING_MODEL_NAME_TITLE 1051
#define IDC_STT_CUR_MODEL_NAME_TIT      1052
#define IDC_STT_HOST_MODEL_NAME_TIT     1052
#define IDC_STT_CUR_MODEL_NAME          1053
#define IDC_STT_HOST_MODEL_NAME         1053
#define IDC_STT_FUSING_STATUS_TIT       1054
#define IDC_BUTTON1                     1054
#define IDC_BUTTON_FLICKER              1054
#define IDC_BUTTON_MODELCOPY_MOD        1054
#define IDC_STT_FUSING_STATUS           1055
#define IDC_COMBO_MODE                  1055
#define IDC_BUTTON_SYSTEM               1055
#define IDC_BUTTON_COPY_MOD2            1055
#define IDC_BUTTON_PATTERNCOPY_MOD      1055
#define IDC_COMBO_VCOM_IC               1056
#define IDC_GRP_FUNCTION                1057
#define IDC_COMBO_VCOM_IC2              1057
#define IDC_COMBO_DATA_SIZE             1057
#define IDC_STT_LOCAL_MODEL_NAME_TIT    1058
#define IDC_STT_LOCAL_MODEL_NAME        1059
#define IDC_CMB_PWR_TYP                 1059
#define IDC_STATIC_STR_CNT              1060
#define IDC_EDT_V_WIDTH                 1061
#define IDC_BTN_EXPOIRT                 1061
#define IDC_BTN_EXPORT                  1061
#define IDC_EDT_VACTIVE                 1062
#define IDC_EDT_VBPORCH                 1063
#define IDC_EDT_VFPORCH                 1064
#define IDC_EDT_H_WIDTH                 1065
#define IDC_EDT_HACTIVE                 1066
#define IDC_EDT_HBPORCH                 1067
#define IDC_EDT_HFPORCH                 1068
#define IDC_EDT_MCLK                    1069
#define IDC_EDT_TSEQ1                   1070
#define IDC_EDT_TSEQ2                   1071
#define IDC_EDT_TSEQ3                   1072
#define IDC_EDT_V_TOTAL                 1073
#define IDC_EDT_H_TOTAL                 1074
#define IDC_EDT_TSEQ4                   1075
#define IDC_EDT_SVCC                    1076
#define IDC_EDT_SVDD                    1077
#define IDC_EDT_SVBL                    1078
#define IDC_EDT_OVCC                    1079
#define IDC_EDT_OVBL                    1080
#define IDC_EDT_LICC                    1081
#define IDC_EDT_LIDD                    1082
#define IDC_EDT_LIBL                    1083
#define IDC_EDT_HICC                    1084
#define IDC_EDT_HIBL                    1085
#define IDC_EDT_HIDD                    1086
#define IDC_EDT_LVCC                    1087
#define IDC_EDT_LVDD                    1088
#define IDC_EDT_LVCC2                   1088
#define IDC_EDT_LVBL                    1089
#define IDC_EDT_LVCC3                   1089
#define IDC_EDT_HVCC                    1090
#define IDC_EDT_HVBL                    1091
#define IDC_EDT_LVCC4                   1091
#define IDC_EDT_HVDD                    1092
#define IDC_EDT_LVCC5                   1092
#define IDC_EDT_PAT_GRAY                1093
#define IDC_EDT_LVCC6                   1093
#define IDC_EDT_SEQOFF_COUNT            1094
#define IDC_EDT_LVCC7                   1094
#define IDC_EDT_Default                 1094
#define IDC_EDT_DEF                     1094
#define IDC_EDT_SVBL2                   1095
#define IDC_EDT_LVCC8                   1095
#define IDC_EDT_CTL_ADDR                1095
#define IDC_EDT_OVBL2                   1096
#define IDC_EDT_RD                      1096
#define IDC_EDT_LIBL2                   1097
#define IDC_EDT_REG_ADDR                1097
#define IDC_EDT_HIBL2                   1098
#define IDC_EDT_WR                      1098
#define IDC_EDT_LVBL2                   1099
#define IDC_EDT_MIN                     1099
#define IDC_EDT_HVBL2                   1100
#define IDC_EDT_DEV_ADDR                1100
#define IDC_EDT_STR_CNT1                1101
#define IDC_EDT_MAX                     1102
#define IDC_EDT_STR_CNT2                1102
#define IDC_STATIC_STR_PWR_ID           1103
#define IDC_EDT_STR_CNT3                1104
#define IDC_EDT_STR_PWR_ID              1104
#define IDC_EDIT_PN                     1105
#define IDC_EDIT_MODEL_NAME             1106
#define IDC_BUTTON2                     1107
#define IDC_EDIT_FOLDER                 1108
#define IDC_BTN_BROWSE                  1109
#define IDC_EDIT_ORACLE_NAME            1110
#define IDC_EDT_MODELSEARCH             1110
#define IDC_EDIT_USER_ID                1111
#define IDC_EDIT_PASSWORD               1112
#define IDC_BUTTON_MODEL_PATH           1115
#define IDC_BUTTON_PATTERN_PATH         1116
#define IDC_CBOX_PORT                   1117
#define IDC_BUTTON_SAVE_PATH            1118
#define IDC_STATIC_RS232                1120
#define IDC_STATIC_MES                  1121
#define IDC_STATIC_CONNECT              1122
#define IDC_STATIC_CONNECT2             1124
#define IDC_STATIC_CONNECT3             1125
#define IDOK                            1126
#define IDC_STATIC_CONNECT4             1126
#define IDC_STT_UI_USERID_TITLE         1127
#define IDC_STT_UI_IMAGE                1128
#define IDC_STATIC11                    1129
#define IDC_STATIC1                     1130
#define IDC_STATIC2                     1131
#define IDC_STATIC3                     1132
#define IDC_STATIC4                     1133
#define IDC_STATIC5                     1134
#define IDC_STATIC6                     1135
#define IDC_BTN_PAT_ADD                 1136
#define IDC_BTN_PAT_DEL                 1137
#define IDC_BTN_PAT_CHG                 1138
#define IDC_BTN_PAT_UP                  1139
#define IDC_BTN_PAT_DN                  1140
#define IDC_STATIC7                     1141
#define IDC_STATIC8                     1142
#define IDC_STATIC9                     1143
#define IDC_STATIC10                    1144
#define IDC_STATIC12                    1145
#define IDC_STATIC13                    1146
#define IDC_STATIC14                    1147
#define IDC_STATIC15                    1148
#define IDC_STATIC16                    1149
#define IDC_CMB_PAT_NAME                1150
#define IDC_LIST_PATVIEW                1151
#define IDC_CMB_MODEL_NAME              1152
#define IDC_CMB_1ST_PTN                 1153
#define IDC_STATIC17                    1154
#define IDC_STATIC18                    1155
#define IDC_STATIC19                    1156
#define IDC_STT_PAT_NAME                1157
#define IDC_STT_PAT_GRAY                1158
#define IDC_STT_1ST_PTN                 1159
#define IDC_STT_SEQOFF_DIN_CNT          1160
#define IDC_STATIC20                    1161
#define IDC_STATIC21                    1162
#define IDC_STATIC22                    1163
#define IDC_STATIC23                    1164
#define IDC_STATIC24                    1165
#define IDC_STATIC25                    1166
#define IDC_STATIC26                    1167
#define IDC_STATIC27                    1168
#define IDC_STATIC28                    1169
#define IDC_STATIC29                    1170
#define IDC_STATIC30                    1171
#define IDC_STATIC31                    1172
#define IDC_STATIC32                    1173
#define IDC_STATIC33                    1174
#define IDC_STATIC34                    1175
#define IDC_STATIC35                    1176
#define IDC_STATIC36                    1177
#define IDC_STATIC37                    1178
#define IDC_STATIC38                    1179
#define IDC_STATIC39                    1180
#define IDC_STATIC40                    1181
#define IDC_STATIC41                    1182
#define IDC_STATIC42                    1183
#define IDC_STATIC43                    1184
#define IDC_STATIC44                    1185
#define IDC_STATIC45                    1186
#define IDC_STATIC46                    1187
#define IDC_STATIC47                    1188
#define IDC_STATIC48                    1189
#define IDC_STATIC49                    1190
#define IDC_STATIC50                    1191
#define IDC_STATIC51                    1192
#define IDC_STATIC52                    1193
#define IDC_STATIC53                    1194

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1195
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
